# Generated by Django 5.2.7 on 2025-10-13 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_original', models.FileField(upload_to='originais/', verbose_name='PDF Original')),
                ('tipo_transfomacao', models.CharField(choices=[('MELHORAR_PDF', 'Melhorar Legibilidade PDF'), ('EXTRAIR_TEXTO', 'Transformar PDF em Texto'), ('TRANSFORMAR_AUDIO', 'Transformar PDF em Áudio')], max_length=50, verbose_name='Tipo de Transformação')),
                ('task_id', models.CharField(blank=True, help_text='ID usado para rastrear o status da tarefa assíncrona.', max_length=255, null=True, verbose_name='ID da Tarefa Celery')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente/Na Fila'), ('PROCESSANDO', 'Em Processamento'), ('SUCESSO', 'Concluído com Sucesso'), ('FALHA', 'Falha no Processamento')], default='PENDENTE', max_length=50, verbose_name='Status da Tarefa')),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='resultados/', verbose_name='Arquivo de Resultado')),
                ('log_processamento', models.TextField(blank=True, null=True, verbose_name='Log/Mensagem de Erro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Processado',
                'verbose_name_plural': 'Documentos Processados',
            },
        ),
    ]
